version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-db
    ports:
      - "3306:3306"
    networks:
      - product-process-network
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - product-process-network
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - product-process-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - product-process-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  app:
    build:
      context: ./product-processing-api
      dockerfile: Dockerfile
      args:
        SPRING_PROFILE: prod
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # DB
      spring.datasource.url: jdbc:mysql://mysql:3306/product-db
      spring.datasource.username: root
      spring.datasource.password: root
      # Kafka
#      spring.kafka.bootstrap-servers: kafka:9092
      # Redis
      redis.host: redis
      redis.port: 6379
      redis.database: 1
    ports:
      - "8080:8080"
    networks:
      - product-process-network

volumes:
  mysql_data:
  redis_data:

networks:
  product-process-network:
    driver: bridge
