version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-db
    ports:
      - "3306:3306"
    networks:
      - product-process-network
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - product-process-network
    volumes:
      - redis_data:/data

  app:
    build:
      context: ./product-processing-api
      dockerfile: Dockerfile
      args:
        SPRING_PROFILE: prod
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # DB
      spring.datasource.url: jdbc:mysql://mysql:3306/product-db
      spring.datasource.username: root
      spring.datasource.password: root
      # Kafka
#      spring.kafka.bootstrap-servers: kafka:9092
      # Redis
      redis.host: redis
      redis.port: 6379
      redis.database: 1
    ports:
      - "8080:8080"
    networks:
      - product-process-network

volumes:
  mysql_data:
  redis_data:

networks:
  product-process-network:
    driver: bridge
